### PR TITLE
Speed up implementation

### PR DESCRIPTION
**Pull request by iegomez**
Hi, @pklaus.
Thank you for creating this package, it really saved my day a couple of weeks ago.
I managed to get some time today and implemented the changes, including an extra command line parameter. I also took your suggestion and defaulted to the number of cores of the machine. You can pass that param with the --cores (or -c) option.

There's one detail with the implementation: the image inverting is done earlier now, so the threshold gets reversed (when you used 70 before, now you need a threshold of 30 to achieve the same result). Also, it depends on PIL.ImageOps, which I had to import. Other further imports are those concerning multiprocessing that I added to the raster file.

### CODE REVIEW

**Comment by dforrer** [comment]
I did some testing on a **raspberry pi 3** with Ignacio's improvements doing this command:
```
brother_ql_create --model QL-720NW --label-size 62x29 -c 4 --loglevel DEBUG --no-cut out.png > out.bin
```

`-c 4` vs `-c 1`:

- using 4 cores is slightly slower than just 1
  executing the same command 5 times in a row with -c 4 takes on average: 4.7s
  with -c 1 it takes 4.5s
- the overhead of the parallelisation seems to outweigh the benefits because of the simplicity of the task

**Comment by pklaus** [comment]
Some comments:

* You are importing `ctypes` in [L23](https://github.com/pklaus/brother_ql/pull/16/files#diff-962c457e4d1586429201652fe08301bfR23) but not actually using it. 
* Another import is `from cStringIO import StringIO` in [L27](https://github.com/pklaus/brother_ql/pull/16/files#diff-962c457e4d1586429201652fe08301bfR27). This works only with Python2. On Python3 this module is gone.
* `cores` should be an optional keyword argument in [L178](https://github.com/pklaus/brother_ql/pull/16/files#diff-962c457e4d1586429201652fe08301bfR178)
* If you invert the picture early on, why don't you also invert the threshold? Then you don't need to change its meaning. Just do `threshold = 100.0 - threshold`. Otherwise we would change the behaviour for our existing users.
* You put the code to invert the picture in [L113](https://github.com/pklaus/brother_ql/pull/16/files#diff-8213167612a8db70c871fda7db8825bdR113) but you didn't remove any of my code there? This cannot make it faster, right?

**Comment by iegomez** [comment]
@dforrer, I thought the parallelisation might do no good, after all these are small label printers, but I don't have a Raspberry Pi to test with yet. How large were the png that you used to get your results? If small, could you try with a really big one to see if multiprocessing is worth at all?

@pklaus Thanks for the comments. You are right, I was in kind of a hurry and forgot to clean things up later. 

- The ctypes import should be gone.
- I wasn't aware the package had changed (I'm kind of new to Python and because of some restrictions I had to go with 2.7). I'll change it to make it compatible.
- Yes, just forgot to add it.
- I'll do the threshold invertion. Let me mention that I'm inverting the image first because it was consistently faster than inverting it later, at least in my test set, but it was a really small difference (and I have no idea why it happened really), so maybe it could be done after the threshold is applied.
- What got removed was the later invertion done in the add_raster_data function, specifically this bit:
```
# The above command directly returns the 1-bit image packed
# into bits. (The cast to bytes is needed for Py2 compatibility.)
frame = bytes([2**8 + ~byte for byte in frame]) # invert b/w
```
That showed to be the main bottleneck of the package and the time reduction by changing it to the new inversion was about 4 or 5 seconds worth (again, on my low-end device).

Anyway, I'll wait to see what @dforrer can report about large pngs. If there is no improvement, then I'll just remove the parallelisation bits (maybe keep them in a separate branch for future testing) and keep only the invertion and the file writing code.

**Comment by iegomez** [comment]
I pushed the commented changes and kept the multiprocessing for now.

**Comment by dforrer** [comment]
I tried using larger PNGs but they would not print. So now I'm using PNGs that match the dimensions of the label exactly, in my case 696x271.

**Comment by dforrer** [comment]
I would keep the multiprocessing but make the default value for c = 1

**Comment by iegomez** [comment]
If @pklaus is ok with leaving the multiprocessing option and defaulting it to 1, I'll make that last change.

Anyway, how much improvement did you get trying my changes with 1 core? I recall that calling the package from command line wasn't that fast (although a lot faster than before), but using the raster module directly in my code took just between 1 and 2 seconds depending in the original PNG. I ask just to know if there's a need for further improvements so we could check it out, or it's sufficiently good right now.

**Comment by pklaus** [comment]
Hi @iegomez!
I finally managed to do some more testing. Note that in my commit 670068c I removed the multiprocessing code. For now, I only merged the code that changes how the inversion is done. This code gives me a consistent speedup of ~20% (when running the `create_label()` function multiple times from within Python on a fast machine).
I will have a further look on the multiprocessing code as well. I found that it helps particularly to speedup the creation of long labels but is increasing the computing time for small labels (no surprise, as the setup of additional processes takes time).
Thanks again for the pull request! The current result is now available as tag v0.7.5 or via [PyPI](https://pypi.python.org/pypi/brother_ql).

**Comment by pklaus** [comment]
There is one more thing about execution speed I just realized: The compression algorithm of the [packbits package](https://pypi.python.org/pypi/packbits/) takes a lot of time. 98% of the call to create_label() is spent there!!!

Currently, compression is automatically enabled on any printer that supports it. See [line146 of brother_ql/brother_ql_create.py](https://github.com/pklaus/brother_ql/blob/3584b6ba5d71ce8e01f9fdc1a0448613555d1f70/brother_ql/brother_ql_create.py#L146).
By forcing it to not use compression, the average runtime spent in create_label() would go down to only 11% (of the time w/ compression enabled).

I think I should add a keyword argument to the function [def create_label(...)](https://github.com/pklaus/brother_ql/blob/3584b6ba5d71ce8e01f9fdc1a0448613555d1f70/brother_ql/brother_ql_create.py#L59) so that the compression can be forced "off". This would be useful on low performance devices (Raspberry Pi 1 etc.).

**Comment by iegomez** [comment]
Hi @pklaus!
Great to here some of the findings were helpful. I agree with the multiprocessing remotion: labels tend to be small in size, so the overhead will likely make it worse most of the time.
Great catch with the compression issue, that should really deal with the speed problem for almost any use.
If you need a hand for any of these, just let me know if I can help.

**Comment by pklaus** [comment]
I finally managed to disable the compression by default. In commit f1fd99f I added a new keyword argument `compress=` to the create_label() function. It's also exposed to the `brother_ql_create` CLI via --compress. This should speed up the label creation in many cases.

**Pull request merged**
